sonar.projectKey=8d6eb12ea811a47b5f4a7468eb62b4e29f913592
sonar.organization=s225659835-design
sonar.host.url=https://sonarcloud.io
sonar.token=${SONAR_TOKEN}

sonar.sources=.
sonar.exclusions=node_modules/**,test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8
